### ISSUE TITLE
Is it possible for CdmGridDatasetFactory to be subclassable again?

### ISSUE THREAD

**Issue by lesserwhirls** [Reading-eScience-Centre/edal-java#103]
Last year, @guygriffiths made`CdmGridDatasetFactory` subclassable be removing the `final` declaration (see [here](https://github.com/Reading-eScience-Centre/edal-java/commit/dd3bff90a84c178803438180dc23a5515b88c9e5#diff-e059ed3454065365fd2b8a1eb462ec54)). In the TDS, we [subclass](https://github.com/Unidata/thredds/blob/5.0.0/tds/src/main/java/thredds/server/wms/TdsWmsDatasetFactory.java) it to handle NcML aggregations. If it's not possible to make `CdmGridDatasetFactory` subclassable, might you suggest another way to go? Thanks!

**Comment by guygriffiths** [comment]
Not sure why that got reverted, I've just done that in the develop branch.

**Comment by lesserwhirls** [comment]
Thanks @guygriffiths!
