### ISSUE TITLE
SimpleCoverageJsonConverterTest fails if default timezone is not UTC 

### ISSUE THREAD

**Issue by MatsSundqvist** [Reading-eScience-Centre/edal-java#123]
line 60 should be 
DateTime time = new DateTime(2000, 01, 01, 00, 00, DateTimeZone.UTC);

**Comment by guygriffiths** [comment]
Thanks, fixed in https://github.com/Reading-eScience-Centre/edal-java/commit/05044a4e73e9a41bbb730699c717b25fddf1c783
