### ISSUE TITLE
Problem with LAYER vs LAYERS

### ISSUE THREAD

**Issue by ethanrd** [Reading-eScience-Centre/edal-java#125]
Requests with `LAYER` parameter returns a `ServiceException`.
The same request succeeds when changed to use `LAYERS`.

The failure occurs at [line 107 in GetMapStyleParams](https://github.com/Reading-eScience-Centre/edal-java/blob/master/wms/src/main/java/uk/ac/rdg/resc/edal/wms/GetMapStyleParams.java#L107):

    if (layerStr != null && !layersStr.trim().isEmpty()) {

looks like `layersStr.trim()` should be `layerStr.trim()` -- dropping the 's' in "layers".

I'm working with the current THREDDS 5.0.0-SNAPSHOT with a dependency on
edal-wms 1.4.2.

**Comment by guygriffiths** [comment]
Thanks for this.  Strangely enough I found this a couple of weeks back, after not working on ncWMS for a long time.  It's fixed in https://github.com/Reading-eScience-Centre/edal-java/commit/1f4544d4d5cf279d1167d131f4f70bc690a55ddc
