### ISSUE TITLE
Unsigned data types not being handled

### ISSUE THREAD

**Issue by ghansham** [Reading-eScience-Centre/edal-java#126]
Dear Sir

We need to handle unsigned data types properly

https://github.com/Reading-eScience-Centre/edal-java/blob/5b962977ee6017cf50f6ea365bcfb273fc76295e/cdm/src/main/java/uk/ac/rdg/resc/edal/dataset/cdm/CdmGridDataSource.java#L457

**Comment by guygriffiths** [comment]
Only unsigned bytes are allowed by the CF conventions, by using the `byte` data type and then specifying the `valid_min` and `valid_max` values.  I've just fixed that and pushed it to `develop`.

**Comment by ghansham** [comment]
Thanks a lot.

**Comment by ghansham** [comment]
Should then such datasets should be rejected at ingestion stage?

**Comment by ghansham** [comment]
You can simplify the logic. There is a data type for UBYTE. Check:

https://github.com/Unidata/netcdf-java/blob/master/cdm/core/src/main/java/ucar/ma2/DataType.java

**Comment by guygriffiths** [comment]
No, I cannot simplify the logic.  Like I said:

> Only unsigned bytes are allowed by the CF conventions, _**by using the `byte` data type**_ and then specifying the `valid_min` and `valid_max` values.

The unsigned byte data type is not supported by the CF conventions.  See here: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_data_types

**Comment by ghansham** [comment]
Okay. Agree. I was trying to say putting the case for UBYTE and not for any
other unsigned data types. Its okay for me.

**Comment by guygriffiths** [comment]
It's probably worth including UBYTE, USHORT, and UINT as well, but the `byte`/`valid_min`/`valid_max` behaviour should stay there (despite being a little unintuitive)

**Comment by jonblower** [comment]
I guess the unsigned stuff in the Unidata Java libraries is there to support other data formats, like BUFR perhaps?
