### ISSUE TITLE
How to do contouring at an interval

### ISSUE THREAD

**Issue by ghansham** [Reading-eScience-Centre/edal-java#127]
Dear Sir

If I have data with range (90, 380) and I want to contour at every 30 interval. Because we have only option to set number of contours. Due to rounding off errors, it plots at an interval of 29.
One option could be we can specify the interval as part of sld which can override the number of levels (if provided).
Second option, we can specify the list of values over which we can contour.

Second option will be more flexible as we can contour at irregular intervals also.

Ghansham

**Comment by guygriffiths** [comment]
Just set the COLORSCALERANGE to values whose difference divides by 30, e.g. `COLORSCALERANGE=90,390`.

**Comment by ghansham** [comment]
Ok
