### ISSUE TITLE
Upgrading netCDF-Java

### ISSUE THREAD

**Issue by lesserwhirls** [Reading-eScience-Centre/edal-java#129]
Greetings!

I ran into an issue a bit earlier this week that required me to recompile and build new edal-java artifacts using a newer version of netCDF-Java (in this particular case, `5.4.0-SNAPSHOT`). Everything went well and didn't require any code changes within edal-java itself. I would recommend bumping to the latest release, which is 5.3.2 (note the `cdm` artifact has become `cdm-core`), and I'd be happy to make a PR for that.

Along the same lines, we are working on defining the public API for the library and have been looking for API testers:

https://www.unidata.ucar.edu/blogs/developer/en/entry/netcdf-java-looking-ahead

We're keeping track of those efforts in a separate repository at the moment, and the details can be found at:

https://github.com/lesserwhirls/netcdf-java-api-testing/wiki

We'd love to have your input if you have any cycles to spare!

**Comment by guygriffiths** [comment]
Sorry for the delay in getting back to you, we don't have a great deal of effort available for ncWMS work at the moment.  I've bumped the version in my development environment and it'll go into the next release.

**Comment by guygriffiths** [comment]
We're now using 5.3.3 in https://github.com/Reading-eScience-Centre/ncwms/releases/tag/ncwms-2.5.0
