### ISSUE TITLE
More glyph-based styles

### ISSUE THREAD

**Issue by guygriffiths** [Reading-eScience-Centre/edal-java#13]
Whilst we have some examples of glyph-based styles for gridded data, it would be desirable to incorporate them as available styles.

**Comment by guygriffiths** [comment]
Glyph styles for gridded data are not really possible with the current data model - features are extracted onto the map domain, which means that we don't have the single-value-per-grid-cell which would be needed for such a visualisation.  Closing

**Comment by jonblower** [comment]
Does this mean we've lost some of the capabilities we had from GeoViQua? Could we not use the values within the map domain to derive the glyphs?

**Comment by guygriffiths** [comment]
This was specifically referring to using the in-situ glyphs on gridded data - i.e. having a coloured icon at the cell centre - which has never really been possible.  The glyph-based stuff from GeoViQua is still in there.

**Comment by jonblower** [comment]
Ah OK
