### ISSUE TITLE
ArrowColourField

### ISSUE THREAD

**Issue by ghansham** [Reading-eScience-Centre/edal-java#131]
I have a following SLD, The ArrowColourField does not get reflected in legendgraphics. Is it what it is intended to do?

<NamedLayer>
    <se:Name>$layerName-dir</se:Name>
    <UserStyle>
      <se:CoverageStyle>
        <se:Rule>
          <resc:ColoredSizedArrowSymbolizer>
            <se:Opacity>100</se:Opacity>
            <resc:ArrowSizeField>$layerName-mag</resc:ArrowSizeField>
            <resc:ArrowColourField>PRESSURE</resc:ArrowColourField>
            <resc:ArrowMinSize>4</resc:ArrowMinSize>
            <resc:ArrowMaxSize>12</resc:ArrowMaxSize>
            <resc:Range>
              <resc:Minimum>$scaleMin</resc:Minimum>
              <resc:Maximum>$scaleMax</resc:Maximum>
            </resc:Range>
            <se:ColorMap>
              <resc:Segment fallbackValue="#00000000">
                <se:LookupValue>Rasterdata</se:LookupValue>
                <resc:BelowMinValue>extend</resc:BelowMinValue>
                <resc:ValueList>
                  <se:Name>insat_irw</se:Name>
                </resc:ValueList>
                <resc:AboveMaxValue>extend</resc:AboveMaxValue>
                <resc:Range>
                  <resc:Minimum>100</resc:Minimum>
                  <resc:Maximum>975</resc:Maximum>
                </resc:Range>
                <resc:NumberOfSegments>250</resc:NumberOfSegments>
              </resc:Segment>
            </se:ColorMap>
            <resc:ArrowStyle>WIND_BARBS</resc:ArrowStyle>
          </resc:ColoredSizedArrowSymbolizer>
        </se:Rule>
      </se:CoverageStyle>
    </UserStyle>
  </NamedLayer>

regards
Ghansham

**Comment by guygriffiths** [comment]
I would need to see the SLD and the request you're using to generate the legend graphics to be able to help out here.

**Comment by ghansham** [comment]
Dear Sir

I have attached the barb.txt. 
Rename it barb.xml

And the legend graphics request is as follows:

http://10.61.141.62:8090/ncWMS2/wms?&WIDTH=400&HEIGHT=400&request=GetLegendGraphic&SLD_BODY=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3CStyledLayerDescriptor%20version%3D%221.1.0%22%20xsi%3AschemaLocation%3D%22http%3A%2F%2Fwww.opengis.net%2Fsld%20StyledLayerDescriptor.xsd%22%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fsld%22%20xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%20xmlns%3Ase%3D%22http%3A%2F%2Fwww.opengis.net%2Fse%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20xmlns%3Axsi%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%22%20xmlns%3Aresc%3D%22http%3A%2F%2Fwww.resc.reading.ac.uk%22%3E%0A%0A%20%20%3CNamedLayer%3E%20%0A%20%20%20%20%3Cse%3AName%3E3DIMG_L2P_IRW%2FUCOMP%3AVCOMP-dir%3C%2Fse%3AName%3E%0A%20%20%20%20%3CUserStyle%3E%0A%20%20%20%20%20%20%3Cse%3ACoverageStyle%3E%0A%20%20%20%20%20%20%20%20%3Cse%3ARule%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cresc%3AColoredSizedArrowSymbolizer%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cse%3AOpacity%3E100%3C%2Fse%3AOpacity%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AArrowSizeField%3E3DIMG_L2P_IRW%2FUCOMP%3AVCOMP-mag%3C%2Fresc%3AArrowSizeField%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AArrowColourField%3E3DIMG_L2P_IRW%2FPRESSURE%3C%2Fresc%3AArrowColourField%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AArrowMinSize%3E4%3C%2Fresc%3AArrowMinSize%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AArrowMaxSize%3E12%3C%2Fresc%3AArrowMaxSize%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3ARange%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AMinimum%3E2.178%3C%2Fresc%3AMinimum%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AMaximum%3E51.72%3C%2Fresc%3AMaximum%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fresc%3ARange%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cse%3AColorMap%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3ASegment%20fallbackValue%3D%22%2300000000%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cse%3ALookupValue%3ERasterdata%3C%2Fse%3ALookupValue%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3ABelowMinValue%3Eextend%3C%2Fresc%3ABelowMinValue%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AValueList%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cse%3AName%3Einsat_irw%3C%2Fse%3AName%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fresc%3AValueList%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AAboveMaxValue%3Eextend%3C%2Fresc%3AAboveMaxValue%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3ARange%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AMinimum%3E100%3C%2Fresc%3AMinimum%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AMaximum%3E975%3C%2Fresc%3AMaximum%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fresc%3ARange%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3ANumberOfSegments%3E250%3C%2Fresc%3ANumberOfSegments%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fresc%3ASegment%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fse%3AColorMap%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cresc%3AArrowStyle%3EWIND_BARBS%3C%2Fresc%3AArrowStyle%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fresc%3AColoredSizedArrowSymbolizer%3E%0A%20%20%20%20%20%20%20%20%3C%2Fse%3ARule%3E%0A%20%20%20%20%20%20%3C%2Fse%3ACoverageStyle%3E%0A%20%20%20%20%3C%2FUserStyle%3E%0A%20%20%3C%2FNamedLayer%3E%0A%0A%20%0A%3C%2FStyledLayerDescriptor%3E









[barb.txt](https://github.com/Reading-eScience-Centre/edal-java/files/5123758/barb.txt)

**Comment by guygriffiths** [comment]
Ok, this was a bug in the code.  It was not detecting the multiple fields required for generating an appropriate legend.  I've fixed this in the `develop` branch, so it should work if you check out that branch and use it.

**Comment by ghansham** [comment]
For sure. I will check it out.
Thanks a lot for your help.

**Comment by ghansham** [comment]
I have checked it. It is working fine for my datasets.
When is the next release expected?

**Comment by guygriffiths** [comment]
Fix released https://github.com/Reading-eScience-Centre/ncwms/releases/tag/ncwms-2.5.0
