### ISSUE TITLE
FORMAT=image/png is 32 bit

### ISSUE THREAD

**Issue by tdrwenski** [Reading-eScience-Centre/edal-java#156]
### Description
`GetMap` requests with either `FORMAT=image/png` or `FORMAT=image/png;mode=32bit` return a 32 bit png. Is this expected behavior? I was told by TDS user that the first option used to return a 8 bit png in TDS 4/ ncWMS 1.

### Reproduction path:

1. With `FORMAT=image/png`
```
> curl 'https://thredds.ucar.edu/thredds/wms/grib/NCEP/GFS/Global_0p25deg_ana/GFS_Global_0p25deg_ana_20230602_1200.grib2?LAYERS=Soil_type_surface&TIME=2023-06-02T12%3A00%3A00.000Z&BGCOLOR=extend&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-294.24,32.88,-171.36,155.76&WIDTH=256&HEIGHT=256&FORMAT=image/png' -o image.png  

> file image.png 
image.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
```

2. With `FORMAT=image/png;mode=32bit`
```
> curl 'https://thredds.ucar.edu/thredds/wms/grib/NCEP/GFS/Global_0p25deg_ana/GFS_Global_0p25deg_ana_20230602_1200.grib2?LAYERS=Soil_type_surface&TIME=2023-06-02T12%3A00%3A00.000Z&BGCOLOR=extend&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-294.24,32.88,-171.36,155.76&WIDTH=256&HEIGHT=256&FORMAT=image/png;mode=32bit' -o image32bit.png

> file image32bit.png 
image32bit.png: PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
```

**Comment by guygriffiths** [comment]
I'm not sure I fully understand, but I don't think either the WMS spec or the MIMEType definition say anything about whether `image/png` is 8- or 32-bit.  The behaviour may possibly have changed since ncWMS1, but I don't think it's unexpected behaviour.

**Comment by tdrwenski** [comment]
Okay, good to know that that is not in the spec so this is expected/ okay behavior. I have not tested with the older version but a TDS user thought this may have been a bug. Thanks!
