### ISSUE TITLE
Refine and document Godiva3 config

### ISSUE THREAD

**Issue by guygriffiths** [Reading-eScience-Centre/edal-java#19]
Some options such as map size etc. can be passed to Godiva3 by running a config servlet.  We should make background layers configurable too, and document how to enable the servlet.  This was developed for MyOcean but hasn't been used outside of that project, when it could easily be incorporated.

**Comment by drf5n** [comment]
Is this the stuff in  https://github.com/Reading-eScience-Centre/edal-java/blob/master/godiva/src/main/java/uk/ac/rdg/resc/godiva/server/ConfigServlet.java ?

**Comment by guygriffiths** [comment]
Yep, that servlet basically takes a `.properties` file and outputs them as JSON which Godiva3 may interpret.  Currently the only options supported by Godiva3 are `mapHeight`, `mapWidth`, and `proxy`.
