### ISSUE TITLE
Parameter vs Variable IDs

### ISSUE THREAD

**Issue by letmaik** [Reading-eScience-Centre/edal-java#23]
The edal.feature.Feature interface refers to parameter IDs. However a Parameter only has a getVariableId method and currently there is no such thing as a parameter ID left (anymore).

I would remove `getParameterIds` from Feature, since this information is easy to get from `getParameterMap`. Then you would be left with `getParameter(String variableId)` and a different description for `getParameterMap`.

**Comment by guygriffiths** [comment]
I've done this, although rather than removing getParameterIds entirely (since it's quite widely used as a convenience method), I've renamed it getVariableIds, which is more accurate
