### ISSUE TITLE
Missing layer names in GetCapabilities statements

### ISSUE THREAD

**Issue by jonescc** [Reading-eScience-Centre/edal-java#27]
Layers that can be referenced in GetMap requests are not named in the GetCapabilities statement.  In fact no layers are named. 

    <Layer queryable="1">
        <Title>sea_water_temperature</Title>
        <EX_GeographicBoundingBox>
            <westBoundLongitude>103.75</westBoundLongitude>
            <eastBoundLongitude>103.75</eastBoundLongitude>
            <southBoundLatitude>-50.25</southBoundLatitude>
            <northBoundLatitude>-3.75</northBoundLatitude>
        </EX_GeographicBoundingBox>
        <BoundingBox CRS="CRS:84" minx="103.75" maxx="161.25" miny="-50.25" maxy="-3.75"/>
        <Dimension name="time" units="ISO8601" multipleValues="true" current="true" default="">
            2009-01-01T00:00:00.000Z/2009-02-12T05:32:18.462Z/P7DT55M23.077S,2009-02-19T06:27:41.538Z/2009-05-14T17:32:18.462Z/P7DT55M23.077S,2009-05-21T18:27:41.538Z/2009-08-14T05:32:18.462Z/P7DT55M23.077S,2009-08-21T06:27:41.538Z/2009-11-13T17:32:18.462Z/P7DT55M23.077S,2009-11-20T18:27:41.538Z/2009-12-25T23:04:36.923Z/P7DT55M23.077S
        </Dimension>
        <Dimension name="elevation" units="m" default="0.0">
            0.0,            10.0,            50.0,            100.0,            200.0,            1000.0,            2000.0,            5000.0        </Dimension>
        <Style>
              ....
        </Style>
    </Layer>

**Comment by guygriffiths** [comment]
Thanks for reporting this.  I've fixed it in the "develop" branch and we'll create a bugfix release in the near future.
