### ISSUE TITLE
using Godiva3 with Dynamic Services

### ISSUE THREAD

**Issue by cehbrecht** [Reading-eScience-Centre/edal-java#32]
i've configured "dynamic services". How can i display them in godiva3? 

Cheers,
Carsten

**Comment by guygriffiths** [comment]
This is not currently possible.  It was planned but was low priority since dynamic datasets were not widely used.  It shouldn't take too long to implement it - certainly we could have something by the end of next week, but I may get a chance to complete it sooner.

**Comment by guygriffiths** [comment]
I have implemented this and it is present in the 1.0.4 release.  To access a dataset in Godiva3, you add the DATASET parameter.  eg:
http://localhost:8080/ncWMS2/Godiva3.html?DATASET=local/datapath/ncfile.nc
