### ISSUE TITLE
Is the demo site down?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#35]
Is the [behemoth demo site](http://behemoth.nerc-essc.ac.uk/ncWMS2/Godiva3.html) referenced in the [ncWMS documentation](http://reading-escience-centre.github.io/edal-java/ncWMS_user_guide.html) down?

**Comment by guygriffiths** [comment]
Yes, it was.  I've restarted it and it's up again.  We do have checking scripts but for some reason it didn't get triggered - I'll look into that now.
