### ISSUE TITLE
Velocity vectors on demo site?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#36]
I was looking to see if velocity vector rendering had changed on the demo site:
http://behemoth.nerc-essc.ac.uk/ncWMS2/Godiva3.html
but I couldn't find any velocity vector layers, only mangitude, speed and u and v components.
Did I miss one somewhere?
If not, could an example be added to the demo client?

**Comment by guygriffiths** [comment]
Velocity vectors can be rendered by clicking on the parent layer which contains the individual components.

**Comment by rsignell-usgs** [comment]
Thanks!  I would not have guessed that, since it looked like just a directory name with the "+" sign next to it.   I tried to select it but the site was not responding.  Maybe down again?

**Comment by guygriffiths** [comment]
We have been having trouble with that server - I've restarted it so it's running for the time being...

If you've any suggestions on how to make it clearer that the parent layer is plottable (which is not necessarily always the case) I'd be happy to implement something.  I've considered underlining the items which can be plotted, but it's a rather ugly solution.  It's an issue we're aware of but it's fairly low priority and we've not had any bright ideas on how to fix it...
