### ISSUE TITLE
Problem getting time series data as CSV: "zeta cannot be downloaded as CSV"

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#48]
I've got a Hurricane Ike simulation as a UGRID dataset that is working nicely with ncWMS2/Godiva3 at
http://geoport.whoi.edu/ncWMS2/Godiva3.html

![2016-03-11_8-12-48](https://cloud.githubusercontent.com/assets/1872600/13703185/0ec19eb0-e762-11e5-9bfa-f85de3c54f27.png)

The time series option works great:

http://geoport.whoi.edu/ncWMS2/wms?REQUEST=GetTimeseries&LAYERS=ADCIRC-IKE-2D-Waves/zeta&QUERY_LAYERS=ADCIRC-IKE-2D-Waves/zeta&BBOX=-96.1858,27.404,-90.9438,31.5976&SRS=EPSG:4326&FEATURE_COUNT=5&HEIGHT=600&WIDTH=750&X=223&Y=316&STYLES=default/default&VERSION=1.1.1&TIME=2008-09-05T12:10:00.000Z/2008-09-17T00:00:00.000Z&INFO_FORMAT=image/png

![2016-03-11_8-13-48](https://cloud.githubusercontent.com/assets/1872600/13703190/140526c6-e762-11e5-94c7-fec672a6811f.png)

but when I try to download this data as CSV (by just switching the `INFO_FORMAT=text/csv`:

http://geoport.whoi.edu/ncWMS2/wms?REQUEST=GetTimeseries&LAYERS=ADCIRC-IKE-2D-Waves/zeta&QUERY_LAYERS=ADCIRC-IKE-2D-Waves/zeta&BBOX=-96.1858,27.404,-90.9438,31.5976&SRS=EPSG:4326&FEATURE_COUNT=5&HEIGHT=600&WIDTH=750&X=223&Y=316&STYLES=default/default&VERSION=1.1.1&TIME=2008-09-05T12:10:00.000Z/2008-09-17T00:00:00.000Z&INFO_FORMAT=text/csv

I get "ADCIRC-IKE-2D-Waves/zeta cannot be downloaded as CSV".   

Is there something I need to configure to allow this?  
Or am I using the wrong syntax on the request?

**Comment by guygriffiths** [comment]
Did you enable downloading in the admin menu? It's disabled by default.

**Comment by rsignell-usgs** [comment]
@guygriffiths , nope, I didn't see that little checkbox. 

Well, that was an easy one!   :smile_cat:
