### ISSUE TITLE
Categorical dataset example?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#49]
The categorical dataset functionality discussed here
http://reading-escience-centre.github.io/edal-java/ncWMS_user_guide.html#Categorical
looks very interesting.

I didn't see a categorical dataset example on the WMS demo site http://behemoth.nerc-essc.ac.uk/ncWMS2/Godiva3.html

Did I miss it?  

If not, could one be added, or is there another example site with categorical data?

**Comment by guygriffiths** [comment]
I think you missed it, unless it had temporarily gone down. It's listed as Melodies Land Cover (Categorical)

**Comment by rsignell-usgs** [comment]
Oops.  I see it now.  Hmmm.....  I would have thought I would have seen that before.   I'm hoping it was temporarily down for my sake.   :blush:
