### ISSUE TITLE
What Java version does ncWMS2 require?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#50]
What Java version does ncWMS2 require?
is there a minimum Tomcat version as well?

I did not find this info in http://reading-escience-centre.github.io/edal-java/ncWMS_user_guide.html
I hope that's not just because I didn't read carefully enough.

**Comment by guygriffiths** [comment]
It needs at least Java 7.  I don't know of a specific minimum Tomcat version, but we use Tomcat 7 for testing.
I'll add it to the user guide tomorrow.

**Comment by rsignell-usgs** [comment]
Awesome.  Thanks!
