### ISSUE TITLE
404 after authentication to <server>/ncWMS2/admin

### ISSUE THREAD

**Issue by rjdave** [Reading-eScience-Centre/edal-java#55]
This is minor because most people probably click the admin link from the main ncWMS2 page. However if you type:

http:/<server>:<port>/ncWMS2/admin

(note the lack of a trailing slash) into the address bar of your browser the authentication window comes up and you can login successfully but you end up at a "404 - The requested resource is not available." if you then add the trailing slash you end up at the expected page without having to re-authenticate.

If you type:

http:/<server>:<port>/ncWMS2

the trailing slash is added automatically but perhaps that's something tomcat is doing.

I am running ncWMS v2.1.2-SNAPSHOT on tomcat 8.0.32 with java 1.8.0_74.

**Comment by guygriffiths** [comment]
Thanks for pointing that out.  I've fixed this in the develop branch so it'll be in the next release.
