### ISSUE TITLE
Bug in common/src/test/java/uk/ac/rdg/resc/edal/util/ExtentsTest.java

### ISSUE THREAD

**Issue by mvtm-dn** [Reading-eScience-Centre/edal-java#59]
Another one issue in unit test linked to timezones. Test fails if current timezone differs from UTC. 
Fix:
=== modified file 'common/src/test/java/uk/ac/rdg/resc/edal/util/ExtentsTest.java'
--- common/src/test/java/uk/ac/rdg/resc/edal/util/ExtentsTest.java	2016-04-07 18:48:35 +0000
+++ common/src/test/java/uk/ac/rdg/resc/edal/util/ExtentsTest.java	2016-07-19 10:40:34 +0000
@@ -31,6 +31,7 @@
 import static org.junit.Assert.*;
 
 import org.joda.time.DateTime;
+import org.joda.time.DateTimeZone;
 import org.junit.Before;
 import org.junit.Test;
 
@@ -215,7 +216,7 @@
         
         Extent<DateTime> datetimeOpenExtent = Extents.newExtent(null, null);
         for (int i = 0; i < 3000; i++) {
-            testDate = new DateTime(i, 1, 1, 0, 0);
+            testDate = new DateTime(i, 1, 1, 0, 0,DateTimeZone.UTC);
             assertTrue(datetimeOpenExtent.contains(testDate));
         }

**Comment by guygriffiths** [comment]
Great thanks.  That'll be fixed in the next release.  Happy to add you as an author in the Javadoc of that class if you let me know the name to put.
