### ISSUE TITLE
default namespace in wms GetCapabilities 1.1.1

### ISSUE THREAD

**Issue by cehbrecht** [Reading-eScience-Centre/edal-java#62]
i'm using the owslib.wms to access the latest ncWMS2 2.2.1. The GetCapabilities xml document defines a default namespace. This troubles the python lxml parser in owslib, so i provided a workaround:

https://github.com/geopython/OWSLib/pull/338

The owslib people say there is no default namespace defined for wms 1.1.1. So, can it be removed in ncWMS2?

**Comment by guygriffiths** [comment]
OK, I've done this - it'll be in the next release.

**Comment by cehbrecht** [comment]
thanks :)
