### ISSUE TITLE
dynamic service with queryable layers

### ISSUE THREAD

**Issue by cehbrecht** [Reading-eScience-Centre/edal-java#65]
i'm using leaflet with the time-dimension plugin to access ncWMS 2.2.1. There is also an example on leaflet with Thredds/ncWMS:

http://apps.socib.es/Leaflet.TimeDimension/examples/example13.html

I'm using the ncWMS2 with tomcat (no Thredds) and dynamic service. I have the problem that the timedimension plugin could not parse the time extent in GetCapabilities document. The reason for this is that it searches only for queryable layers:

https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.layer.wms.js#L277

But the GetCapabilities document didn't have this attribute:

    <Layer>
       <Name>cache/malleefowl/esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/EUR-11/MPI-CSC/MPI-M-MPI-ESM-LR/historical/r1i1p1/MPI-CSC-REMO2009/v1/day/tasmax/v20160419/tasmax_EUR-11_MPI-M-MPI-ESM-LR_historical_r1i1p1_MPI-CSC-REMO2009_v1_day_20010101-20051231.nc/tasmax</Name>
     <Title>tasmax</Title>

The ncWMS2 config for dynamic services has the "queryable" flag set. Shouldn't then all layers have the queryable attribute?

Cheers,
Carsten

**Comment by guygriffiths** [comment]
Yes they should, and now in the next release they will :)
