### ISSUE TITLE
Allow getTimeseries download as text/json

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#73]
It would be nice to allow `getTimeseries` to have an `INFO_FORMAT` of `text/json` so that clients other than godiva3 could more easily access and plot the data (I'm thinking here of Terriajs...).   It's more of a pain to parse `text/xml`.

**Comment by jonblower** [comment]
Yes, we should use [CoverageJSON](https://covjson.org) for this

**Comment by rsignell-usgs** [comment]
Uh oh, now CoverageJSON is out of the bag!  ;-)

**Comment by guygriffiths** [comment]
`text/xml` isn't a supported format for `getTimeseries` - are you thinking of `text/csv`?

Either way, I'll implement support for `text/json` and more specifically `application/prs.coverage+json` for both `getTimeseries` and `getVerticalProfile` and have them return CoverageJSON.

**Comment by rsignell-usgs** [comment]
@guygriffiths , oh, I guess that was the old ncWMS?  Or maybe i was confused.   In any case, it will be nice to have json!  Thanks!   And CoverageJSON looks super cool!

**Comment by guygriffiths** [comment]
OK, this is done in the develop branch.

**Comment by rsignell-usgs** [comment]
Is there an ETA for this functionality arriving in a ncWMS war file?

**Comment by guygriffiths** [comment]
Not at the moment, no.  There's a bug in ncWMS 2.2.4 which occurs if a user wants to define a Tomcat context for ncWMS2 to tell it where to put the config directory.  The Tomcat context overwrites the context included with ncWMS2 which defines how to handle reprojection (necessary since we started using Apache SIS in EDAL 1.2.4), and only a small handful of projections end up being supported.

We're currently discussing workarounds with a chap from Apache, but we can't do a release until this is fixed.

**Comment by rsignell-usgs** [comment]
Okay, thanks for the update and explanation.

**Comment by rsignell-usgs** [comment]
@guygriffiths , any updates here?

**Comment by guygriffiths** [comment]
@rsignell-usgs No, not at the moment, sorry.  I'll try and find some time this week to chase it up, but the majority of my time at the moment is taken up by other projects.

**Comment by rsignell-usgs** [comment]
@guygriffiths , that would be great.   The Unidata THREDDS Steering Team met last week and was discussing ncWMS2 features to be including in the upcoming TDS 5.0 release, and it would be great to have this in there.

**Comment by guygriffiths** [comment]
@rsignell-usgs I managed to find a (horribly hacky) workaround to the Apache issue and I've just done a release which contains these changes

**Comment by rsignell-usgs** [comment]
@guygriffiths , cool!   I see the new ncWMS artifact here:
https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-2.2.5/ncWMS2.war
Thanks!

**Comment by rsignell-usgs** [comment]
This version 2.2.5 has been included in the Docker container here: 
https://hub.docker.com/r/axiom/docker-ncwms/
Container deployed here:
gamone.whoi.edu/ncWMS
and proof that `text/json` is working here:
http://gamone.whoi.edu/ncWMS/wms?REQUEST=GetTimeseries&LAYERS=COAWST/salt&QUERY_LAYERS=COAWST/salt&BBOX=-72.7557,40.6738,-68.3175,44.2302&SRS=CRS:84&FEATURE_COUNT=5&HEIGHT=601&WIDTH=750&X=380&Y=327&STYLES=default/default&ELEVATION=-0.03125&VERSION=1.1.1&TIME=2016-11-14T00:00:00.000Z/2016-11-15T00:00:00.000Z&INFO_FORMAT=text/json
