### ISSUE TITLE
Why is downloadable disabled by default?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#74]
I'm just curious:  why is `downloadable`, required to download `getTimeseries` as `text/xml`, disabled by default?

**Comment by jonblower** [comment]
Because some data providers are happy to make images of their data available, but not to expose the actual data. Hence we make this an opt-in process.

**Comment by rsignell-usgs** [comment]
Sadness.   IMHO it would be better to allow folks to opt out if they didn't want their data shared.    Just my $0.02.
