### ISSUE TITLE
Build fails, unidata libs are missing

### ISSUE THREAD

**Issue by yosoyjay** [Reading-eScience-Centre/edal-java#75]
Build fails for edal, and ncWMS, because the specified versions are no longer available at ucar.

The problem seems to have occurred last month as well as was fixed with commit 7b7ae137fa536cdf86bd870b9a44a791340b953c.

**Comment by guygriffiths** [comment]
@lesserwhirls - Any way we can get around this?  We just need some snapshot versions which won't go away.  We could just rely on 5.0.0-SNAPSHOT, but I'd prefer to have a fixed version which we've tested.

**Comment by lesserwhirls** [comment]
@guygriffiths - sorry for the delay. I just turned off the removal of snapshots from our nexus repo, so they should not disappear until we get a 5 release out. So, you should be able to pin a snapshot until then.

**Comment by Brictarus** [comment]
Hi there. @guygriffiths : could edal-java rely on **released version** for its dependencies, instead of snapshots ? Thx.

**Comment by guygriffiths** [comment]
@Brictarus No.  We want to use v5 of the unidata libs for several reasons and there are no released versions as yet.
