### ISSUE TITLE
GetLegendGraphic STYLES should be optional?

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#81]
After discussion with @kring, it seems that the issue [I reported as a TerriaJS issue](https://github.com/TerriaJS/terriajs/issues/2338) is likely a edal-java issue.

The TerriaJS GetLegendGraphic request:
http://gamone.whoi.edu/ncWMS/wms?service=WMS&version=1.1.0&request=GetLegendGraphic&format=image%2Fpng&transparent=True&layer=Inundation_hampton%2Fflood_index&colorscalerange=-50%2C50
returns the response:
```
<ServiceException>
You must specify either SLD, SLD_BODY or LAYERS and STYLES for a full legend. You may set COLORBARONLY=true to just generate a colour bar
</ServiceException>
```
Yet, looking in [the WMS spec](http://portal.opengeospatial.org/files/?artifact_id=22364), section 10.2.1,  Table 8 shows that STYLES is optional:
![2017-01-19_19-44-15](https://cloud.githubusercontent.com/assets/1872600/22132561/b6993b3e-de88-11e6-9695-d5b90865d2e1.png)

**Comment by guygriffiths** [comment]
OK, the trouble was that STYLES is supposed to be mandatory for GetMap requests and we were using the same code.  I've relaxed that restriction, so GetMap requests will still work if STYLES is missing.  I guess technically it's not what a WMS should do, but I can't imagine a client which would rely on GetMap failing if STYLES is not present...
