### ISSUE TITLE
Godiva3 default depth

### ISSUE THREAD

**Issue by frizwi** [Reading-eScience-Centre/edal-java#89]
Hi, Godiva2 used to display the top vertical layer as default, Godiva3 now shows the bottom layer - is that a configuration in ncWMS/WMS or something else?
Similarly the vertical profile is inverted.
Thanks

**Comment by guygriffiths** [comment]
The default behaviour should be to pick the closest vertical layer to the surface - i.e. the top vertical layer for a depth axis, but the bottom vertical layer for a height axis.

It looks like this is currently not working for axes with units of pressure, which are also being incorrectly labelled as "Depth", when pressure is generally used as a substitute for height.  I'll fix this bug - can you confirm that that's the issue you're seeing?

If you're getting this problem with a genuine depth axis (e.g. ocean levels) then it will need further investigation.

**Comment by frizwi** [comment]
Not entirely sure on the conventions but here are the attributes of the vertical coordinate:


zc: Array of 64 bit Reals [k = 0..46]
units: m
positive: up
long_name: Z coordinate
axis: Z
coordinate_type: Z


i.e. the values are negative for depth in the ocean. Anyway, I guess my point is that the same exact file behaves differently in the Godiva2 vs Godiva3 or maybe more accurately, ncWMS vs ncWMS2.


Let me know if you'd like any more info.


Cheers,

-Farhan


________________________________

**Comment by guygriffiths** [comment]
Is it possible for you to make the file available for me to download?  If not, I can mock it up, but it's a lot easier with (at least a sample of) the real data.

**Comment by frizwi** [comment]
Sure, you should have access to this one:

http://data1.tpac.org.au/thredds/catalog/tascem/setas/catalog.html?dataset=tascem/setas/setas_simple_2017-04.nc

________________________________

**Comment by guygriffiths** [comment]
OK, I've made it so that coordinates are sorted in the correct way.  I'll probably do a 2.2.8 release in the next couple of days, which will include this change.

Another way to work around this is to provide your z axis values as positive depths (as opposed to negative heights)

**Comment by frizwi** [comment]
Thanks, I'll wait for the next release.


________________________________

**Comment by guygriffiths** [comment]
Released
