### ISSUE TITLE
Godiva3 base layers

### ISSUE THREAD

**Issue by frizwi** [Reading-eScience-Centre/edal-java#90]
The top 2 Godiva3 base layers, "Natural Earth" and "Blue Marble" WMS don't seem to be resolving and hence no background shows up. Is this something that's a known issue and will be fixed soon? Or else is there a way to set the "Demis" the default - as all the rest work just fine.
Thanks

**Comment by guygriffiths** [comment]
We host both of these layers at the University of Reading.  They are fine from where I am, but that's on campus and I know there have been some changes with IT recently.

Can you confirm whether or not this link works:
http://godiva.reading.ac.uk/geoserver/ReSC/wms?LAYERS=naturalearth&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=-180,-90,180,90&WIDTH=1024&HEIGHT=512

If there is a problem with that, I will need to speak to IT and let them know that that URL should be available externally.

**Comment by frizwi** [comment]
No the link does not work. Hangs and then eventually times out.


________________________________

**Comment by guygriffiths** [comment]
OK, thanks.  I've asked our IT department to sort it out - if it doesn't get sorted within a week or so, I'll look into a workaround.

**Comment by guygriffiths** [comment]
This is now fixed

**Comment by frizwi** [comment]
Still not working
