### ISSUE TITLE
NCWMS in UGRID unstructured grid with start_index=1

### ISSUE THREAD

**Issue by drf5n** [Reading-eScience-Centre/edal-java#95]
I don't have a public-facing TDS endpoint for my data, but I was using TDS5.0.0 (http://www.unidata.ucar.edu/software/thredds/v5.0/tds/TDS.html) with the built-in WMS and Godiva3, and the WMS did not seem to recognize the start_index=1 attribute* on the connectivity matrix, and slowly produced a scrambled graphic.  I built a zero-based connectivity array with NCO and aggregated it with NCML and adjusted the mesh variable to point to the new array on the server in order to refer to the new face_node_connectivity array, but this did not seem to fix the problem.

I then copied the 0-indexed NCML file to a new file to see if it was some sort of caching issue somewhere, and the issue seemed to resolve.

I have two questions:

1) Does NCWMS interpret the start_index=1 attribute on the connectivity arrays?

2) Does NCWMS (or TDS) cache the geometry somewhere and not recognize updates in the .ncml files?  How can I clear the cache?

* http://ugrid-conventions.github.io/ugrid-conventions/#zero-or-one-based-indexing

**Comment by guygriffiths** [comment]
ncWMS supports the `start_index` attribute, and has done since UGRID support was added.  However, there is at least one known bug (https://github.com/Reading-eScience-Centre/edal-java/issues/84) which can cause scrambled images.  Could this be the issue?

**Comment by drf5n** [comment]
I don't think so. not sure.  My US-east coast domain does have areas/islands/bays within land masses, but it does not cross the date line.

I don't think so.  After swapping the zero-based array in and back out, and adding lots of memory and some additional processors to the virtual machine this was running on, I cannot duplicate the error.  I recommend closing.

**Comment by drf5n** [comment]
I still cant duplicate the error.  closing
