### ISSUE TITLE
Configuration of ncWMS within TDS?

### ISSUE THREAD

**Issue by drf5n** [Reading-eScience-Centre/edal-java#96]
The documentation at https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/03-config.html suggests editing the configWMS.xml file or preferably using the .../ncWMS2/admin web interface.  However the web interface does not appear to be accessible at the documented location.  I tried a few locations, but none seemed to work.

* http://localhost:8080/ncWMS2/admin 
* http://localhost:8080/thredds/ncWMS2/admin 
* http://localhost:8080/thredds/ncWMS/admin 
* http://localhost:8080/thredds/wms/admin 

In TDS, what endpoint would deliver the suggested /admin/ interface?

**Comment by guygriffiths** [comment]
The documentation you reference is for ncWMS, not TDS.  As far as I'm aware, there is no web interface for configuring WMS within TDS.

TDS/WMS documentation is available here:
https://www.unidata.ucar.edu/software/thredds/v4.6/tds/reference/WMS.html

**Comment by drf5n** [comment]
Thanks.  That answers my question.  

On looking into my actual TDS5 wmsConfig.xml file, I notice it points to http://www.met.reading.ac.uk/resc/home/trac/myocean-tools/wiki/WmsDetailedConfiguration for more info, but fixing that broken link would be a TDS issue.
